## Title for page ##

$$a = b + c$$

In [5]:
print('Hello world!')

Hello world!


In [9]:
'Hello world!'

'Hello world!'

In [10]:
2.5 * 3

7.5

In [11]:
3 ** 3

27

In [12]:
3 + 3

6

In [13]:
"ab" + "cd"

'abcd'

In [14]:
"Hello" == 'Hello'

True

In [15]:
a = 3

In [16]:
a

3

In [17]:
type(a)

int

In [18]:
a+a

6

In [19]:
2+a

5

In [34]:
%pylab inline

Populating the interactive namespace from numpy and matplotlib


In [35]:
a = array([1,2])

In [36]:
a

array([1, 2])

In [37]:
type(a)

numpy.ndarray

In [38]:
a.shape

(2,)

In [39]:
a+a

array([2, 4])

In [40]:
2+a

array([3, 4])

In [41]:
a = "Hello world!"

In [42]:
a

'Hello world!'

In [43]:
type(a)

str

In [44]:
a+a

'Hello world!Hello world!'

In [45]:
2+a

TypeError: unsupported operand type(s) for +: 'int' and 'str'

In [46]:
a = array([1,2])

In [47]:
a

array([1, 2])

In [48]:
b = a

In [49]:
b

array([1, 2])

In [50]:
a

array([1, 2])

In [51]:
b[0] = 0

In [52]:
b

array([0, 2])

In [53]:
a

array([0, 2])

In [54]:
c = a.copy()

In [55]:
c[1] = 7

In [56]:
c

array([0, 7])

In [57]:
a

array([0, 2])

In [58]:
a = 4

In [59]:
type(a)

int

In [60]:
a = 4.
type(a)

float

In [62]:
a = 1.5 + 0.1j
type(a)

complex

In [63]:
a.real

1.5

In [65]:
a.imag

0.1

In [66]:
flag = (3>4)
flag

False

In [67]:
type(flag)

bool

In [68]:
type(True)

bool

In [69]:
float(1)

1.0

In [70]:
3/2

1.5

In [71]:
3/2.

1.5

In [72]:
3//2

1

In [73]:
'Hello' == "Hello"

True

In [74]:
a = """This is a multiline string
nifty huh?"""

In [75]:
a

'This is a multiline string\nnifty huh?'

In [77]:
print("\nu")


u


In [78]:
print(r"\nu")

\nu


In [79]:
a = 3.1415

In [80]:
"Blah " + str(a)

'Blah 3.1415'

In [81]:
"Blah %1.2f, %s" % (a, "hi")

'Blah 3.14, hi'

In [82]:
"Blah {:1.2f}, ()".format(a, "hi")

'Blah 3.14, ()'